name: Testing
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    name: Testing for Node v${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11.0
          - ubuntu-20.04
          - windows-2019
        node-version:
          - 12
          - 14
          - 15
          - 16
    steps:
      - uses: actions/checkout@v2
        name: Checking out repository
      - uses: actions/setup-node@v2
        name: Installing nodejs
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
        name: Installing dependencies
      - run: npx eslint src
        name: Testing linting
      - run: yarn test
        name: Unit testing
